proposals/thread-spawn/Overview.md
More examples would be nice, but at least this fills in the gaps and gives some visual idea of what to expect from `shared` attributes.
=> [thread-spawn] Add WAT example

proposals/thread-spawn/Overview.md
After many discussions on the topic, including [this one], there seems to be early consensus on needing to do something along the lines of this proposal but there are differing views on the specific form this might take. I fully expect the proposal to change with more discussion and especially as we prototype and troubleshoot the idea. To capture this in the proposal, I added text indicating how critical each addition is: e.g., if we removed `shared` attributes, this proposal should be closed and replaced by another one. This level of criticality varies for each addition.
[this one]: https://github.com/abrown/thread-spawn/discussions/1
=> [thread-spawn] Mark additions with their criticality to the proposal

proposals/thread-spawn/Overview.md
As discussed [here], limiting which function types can be spawned is... well, limiting. Previously, only allowing a single `i32` parameter meant that toolchains would have to create a closure, likely in shared memory, in order to pass more information to the spawned thread. This would make sense when the implementation uses `pthread_create`, e.g., but could be limiting in other cases.
[here]: https://github.com/abrown/thread-spawn/discussions/3#discussioncomment-6413098
Though that discussion never pinpointed any specific languages where this might be a problem, the limit was a bit artificial. I propose we start with a proposal that is as general as possible and whittle down from there. This change allows the spawned function to take any Wasm parameters with the understanding that this …
=> [thread-spawn] Allow more function types to be spawned

README.md, proposals/shared-everything-threads/Overview.md
@tlively, @conrad-watt: this changes the top-level naming and paves the way for future changes. I figured a warning on the overview page is enough for now while we hack on the document.
=> Migrate to use 'shared-everything-threads' naming

proposals/shared-everything-threads/Overview.md
PR #23 introduced a new line I missed during review that breaks the
Markdown table; this change fixes that.
=> Fix table formatting

proposals/shared-everything-threads/Overview.md
- Note why we add a shared annotation to element segments.
- Restrict thread-local globals to be defaultable with default initializers.
- Update TLS function wrappers in the JS API to be thread-local instead of realm-local.
=> Update overview with feedback from subgroup meeting

proposals/shared-everything-threads/Overview.md
Clarify that only anyref and its subtypes may be atomically accessed, but no access to any reference type should tear. Add validity notes for instructions that were missing them.
Fixes #31.
=> Expand notes on atomic access validity

proposals/shared-everything-threads/Overview.md
Add a generic constructor for shared abstract heap types to use less of the encoding space and describe encodings for shared element segments, data segments, and tags.
=> Update the binary format

proposals/shared-everything-threads/Overview.md
- Use the `shared` constructor bytes for composite types (e.g. func, struct, and array) as well as abstract heap types.
- Use the same bit to encode sharedness in element and data segments.
=> Update binary format again

proposals/shared-everything-threads/Overview.md
The interface for thread-local function wrappers is meant to be similar to and compose with that of JSPI since they both involve wrapping JS functions to affect how they are imported. Since the JSPI interface changed, add a note that we should consider changing the thread-local function interface, too.
=> Add a note about JSPI changes

proposals/shared-everything-threads/Overview.md
Explicitly say that we would expect toolchains to switch almost entirely to using `shared` items rather than frequently mixing them with unshared items.
=> Update note on toolchain use

proposals/shared-everything-threads/Overview.md
This instruction was originally discussed in
https://github.com/WebAssembly/threads/issues/15, but did not make it into the original threads spec.
=> Add `pause` to improve spinlock efficiency

proposals/shared-everything-threads/Overview.md
Also explain that other allocation instructions do not need shared versions.
=> Add `ref.i31_shared` to created shared i31 references

proposals/shared-everything-threads/Overview.md
As discussed in #30 and #37, add a JS API that allows arbitrary objects to be wrapped and converted to shared externrefs with dynamic checks ensuring the wrapped object is only ever observed on the original thread. Refer to the existing FAQ entry for discussion on how the lifetimes of the wrapper and wrapped object might interact.
Resolves #37.
=> Add Thread-Bound Data to the documented JS API

proposals/shared-everything-threads/Overview.md
Instead of a table, give the attribute grammar for waitqueue, shared abstract heap types, and `sharecomptype` to make the syntactic classes clearer. Also remove the binary format note for tags; as previously mentioned, the syntax of tags does not need to change because their sharedness comes from their function type.
Partially resolves #64.
=> Clarify binary format

proposals/shared-everything-threads/Overview.md
Redefine the existing syntax for shared memories as an abbreviation that expands to the new syntax that is more consistent across all kinds of shared items. Add a section on reference types documenting abbreviations like `(shared anyref)`.
This is a more complete alternative to #63
=> Document the text format for shared annotations

proposals/shared-everything-threads/Overview.md
Fix the ref.eq typing to require that both operands have the same
sharedness and list the other instructions that will need to be updated
to use an unconstrained sharedness metavariable in their typing rules.
Resolves #76.
=> Update ref.eq typing and list similar instructions

proposals/shared-everything-threads/Overview.md
Add separate `release` and `acquire` encodings since an `acquire-release` fence is not the same as an `acquire` fence. Encode all orderings as `u8` instead of `u32` and in the case of memory instructions, use a bit in the memarg to signal the presence of a separate ordering immediate rather than encoding the ordering directly in the memarg. For RMW ops, pack both a read ordering and a write ordering into the single `u8` ordering immediate.
This design is similar to the one described in
https://github.com/WebAssembly/shared-everything-threads/issues/60#issuecomment-2136475267, but uses `release` and `acquire` instead of `release-acquire` for load and store orderings, using `release-acquire` only for fences.
Fixes #59.
Fixes #60.
=> Update memory ordering encodings

proposals/shared-everything-threads/Overview.md
Using type variables to allow instructions to be polymorphic over the
sharedness of their inputs allows for principle typing (up to type
variables), but it does not allow for forward principle typing, since
there is no most-precise instantiation of the type variable to choose
when the available input is a bottom stack. For example, this code
sequence could produce either a `(ref any)` or a `(ref (shared any))`:
```
(unreachable) (any.convert_extern)
```
To fix this, instead introduce a bottom shareability, `bot-share`, that
is analogous to the bottom heap type and used only for validation.
~Besides fixing the forward principle typing property and validation in
unreachable code, this also causes mixed-shareability `ref.eq` to be
allowed again since there is no longer a mechanism for …
=> Change from type variables to bot-share for polymorphism

proposals/shared-everything-threads/Overview.md
As discussed at the threads subgroup meeting on December 10, 2024.
Resolves #87.
=> Describe rules for tearing accesses

proposals/shared-everything-threads/Overview.md
In particular, clarify that the type of the expected value operand to
cmpxchg can be a supertype of the field type. This gives optimizers like
Binaryen more leeway to refine field types because they are constrained
by only the type of the replacement operand and not by the type of the
expected value operand.
=> Add typing details for cmpxchg and other rmw operations

proposals/shared-everything-threads/Overview.md
The example in `Overview.md` had some confusing inaccuracies due to changes in syntax over the lifetime of this proposal.
=> Fix inaccuracies in the overview example
